### ISSUE TITLE
Wrong reference number?

### ISSUE THREAD

**Issue by gdikov** [Uehwan/rmd#1]
Hi @Uehwan,

First, thank you for your work!

In your paper on page 4 under **Section 3.1, Illumination variation** you discuss _Depth-error weighted (DW) SSIM_ and cite 

> [32] Hanhan Li, Ariel Gordon, Hang Zhao, Vincent Casser, andAnelia Angelova.   Unsupervised monocular depth learningin dynamic scenes.arXiv preprint arXiv:2010.16404, 2020.

however, after reading [32] I couldn't find any mentioning or description of DW-SSIM. Later on page 6 under **Section 4.2, Technical issues** you also suggest stabilising the network with a precision regularisation, for which you also cite [32]. In this case too, I couldn't find any relation between the prior work and the proposed technique.

Could it be that you refer to [32] by mistake in both cases or am I missing something there? 

Thanks again and best regards,
Georgi

**Comment by Uehwan** [comment]
Thank you for your attention!

The depth error weighted SSIM and the inverse of the variance of depth maps as a loss are not mentioned in the paper [32] as you've point out. In fact, I borrowed the two techniques from their Github code.

I tried to find proper reference papers for the two techniques but I couldn't.
It seemed that the authors of [32] first formulated the two techniques.
If you find proper reference papers, please let me know :)

Thanks!

**Comment by gdikov** [comment]
Thanks for your quick response! 

In case someone else needs that:
 * the variance regularization can be found here: https://github.com/google-research/google-research/blob/master/depth_and_motion_learning/losses/loss_aggregator.py#L220
 * and the DW-SSIM weights are computed here: https://github.com/google-research/google-research/blob/master/depth_and_motion_learning/consistency_losses.py#L114 

I will let you know if I find a paper reference for any of those techniques.
